### ISSUE TITLE
Potential point of comparison with Thomas Streicher's model refuting funext

### ISSUE THREAD

**Issue by jozefg** [AndrasKovacs/antifunext#1]
(I guess this is more discussion point than an issue :) )

This is a very nice model construction!

Reading it, I think it may be closely related to a model Streicher gave in his Habilitation thesis to refute function extensionality. His approach builds on realizability but I think this is really orthogonal for the funext refutation bit. It essentially extends each object with "potential" and "actual" inhabitants and he further restricts to objects with a certain distinguished potential object (roughly, `err`). The idea is then that `Id(x,y)` contains (distinct) real and potential inhabitants if `x = y` but only the potential inhabitant if `x /= y`. The `J` eliminator is then defined to map the potential object/err object to the potential err object of all other constructions and various other elimination principles follow this design. The refutation of funext seems to again hinge on a very similar type to the one considered in this formalization.

For reference, this takes place in Chapter 3 of the thesis with Definition 3.6 isolating those types with a distinguished error element and Definition 3.8 defining the identity type. The refutation of funext is Theorem 3.16. There's a scanned pdf here (NB, big pdf!) https://www2.mathematik.tu-darmstadt.de/~streicher/HabilStreicher.pdf

I guess it might be interesting to see this as a version of Streicher's model which teases apart the realizability and gluing halves into what is needed to model impredicativity (realizability) and what is needed to refute funext (the gluing bit). It also helps (me at least) that your presentation is a bit more modern in terms of language and its focus on Martin-Loef type theory.

**Comment by AndrasKovacs** [comment]
Thanks! Yes, it seems to be the same idea. I'll also mention the Pédrot-Tabareau paper that seems to be the most relevant: https://people.mpi-sws.org/~dreyer/papers/pedrot-exceptional/paper.pdf
